### ISSUE TITLE
Client feedback

### ISSUE THREAD

**Issue by JayHoltslander** [jonathanbossenger/clear-divi-page-builder-cache#3]
Installed this plugin on a client's site who was having constant Builder Cache warnings in their MS browser. Asked them to let me know if it resolved the issue.

>I have gone into the site again and the warning still comes up, but once I close it, it will let me do the work required. I cleared the browser cache again, but it didn’t make a difference. - Client

Any suggestions I can pass on?

**Comment by jonathanbossenger** [comment]
@JayHoltslander this plugin was not really designed to solve any issues with the page builder from a users perspective, more to clear the builder cache when developing third party Divi modules.

Usually that warning is usually related to a memory issue, but as I have never experienced it myself I cannot say for sure. Some time ago I released this plugin which may or may not resolve the problem. https://elegantmarketplace.com/downloads/fix-the-divi-builder-error/. Alternatively there are some comments below that plugin which may also help.

My I also suggest you join the [Divi Theme Users group on Facebook](https://www.facebook.com/groups/DiviThemeUsers/), there are a lot of knowledgeable folks there who would probably be able to help.
